/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cyber.app;

import java.awt.Component;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Gearnest
 */
public class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    static ServerSocket ss;
    static ArrayList sockets = new ArrayList<Socket>();
    static Thread coneccionThread;
    static ArrayList computadoras = new ArrayList<Computadora>();
    boolean someConnection = false, foundIp = false;
    String ip, interfaceStr;
    
    public Servidor() {
        initComponents();
        initServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        equipoPanel = new javax.swing.JPanel();
        noConnection = new javax.swing.JLabel();
        bitácoraPanel = new javax.swing.JPanel();
        configuracionPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        equipoPanel.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        noConnection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noConnection.setText("No hay computadoras conectadas");
        equipoPanel.add(noConnection);

        jTabbedPane1.addTab("Equipos", equipoPanel);

        bitácoraPanel.setLayout(new java.awt.GridLayout(1, 0));
        jTabbedPane1.addTab("Bitácora", bitácoraPanel);

        configuracionPanel.setLayout(new java.awt.GridLayout(1, 0));
        jTabbedPane1.addTab("Configuración", configuracionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Servidor serv = new Servidor();
                
                serv.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                serv.setLocationRelativeTo(null);  
                serv.setVisible(true);
                
            }
        });
    }
    
    public void initServer(){
        // Obtiene información de las interfaces de red con ips
        try{
            ip = "<html>No hay computadoras conectadas.";
            Enumeration<NetworkInterface> nets = NetworkInterface.getNetworkInterfaces();
            for (NetworkInterface netint : Collections.list(nets)){
                foundIp = false;
                interfaceStr = "<br><br>IP " + netint.getName() + ":";
                Enumeration<InetAddress> inetAddresses = netint.getInetAddresses();
                for (InetAddress inetAddress : Collections.list(inetAddresses)) {
                    foundIp = true;
                    interfaceStr += "<br>" + inetAddress;
                }
                if(foundIp)
                    ip += interfaceStr;
            }
            ip += "<html>";
            noConnection.setText(ip);
        } catch (Exception e){}
        
        //Inicializa servidor
        try {
            ss = new ServerSocket(1201);
        } catch (Exception e) {
        }
        Servidor s = this;
        //Inicializa socket
        coneccionThread = new Thread(new Runnable() {
            public void run() {
                System.out.println("Corriendo Gestor de conexiones");
                while (computadoras.size() < 8) {
                    try {
                        // Servidor acepta conecciones
                        sockets.add(ss.accept());
                        System.out.println("Conección realizada");
                        computadoras.add(new Computadora(s, (Socket) sockets.get(sockets.size() - 1), "PC - " + sockets.size()));
                        ((Computadora) computadoras.get(computadoras.size() - 1)).start();
                        ((Computadora) computadoras.get(computadoras.size() - 1)).bloquea();
                        // Inicializa componentes
                        ((Computadora) computadoras.get(computadoras.size() - 1)).setUpComponents();
                    } catch (Exception e) {
                    }

                }
            }
        });
        coneccionThread.start();
    }
    
    public void eliminaComputadora(String nombre){
        for(int i = 0; i < computadoras.size(); i++){
            if(((Computadora)computadoras.get(i)).nombrePC.equals(nombre)){
                computadoras.remove(i);
                sockets.remove(i);
                
                Component[] comps = equipoPanel.getComponents();
                equipoPanel.remove(comps[i]);
                equipoPanel.validate();
                equipoPanel.repaint();
                
                System.out.println("PC "+nombre+" eliminada");
                System.out.println("Cuenta "+computadoras.size());
            }
        }
        if(computadoras.isEmpty()){
            System.out.println("No hay conecciones");
            someConnection = false;
            equipoPanel.add(noConnection);
            equipoPanel.validate();
            equipoPanel.repaint();
        }
    }
    
    public void agregaPCPanel(javax.swing.JPanel PC){
        someConnection = true;
        if(someConnection){
            System.out.println("Borrando");
            equipoPanel.remove(noConnection);
        }
        
        equipoPanel.add(PC);
        equipoPanel.validate();

        equipoPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bitácoraPanel;
    private javax.swing.JPanel configuracionPanel;
    private javax.swing.JPanel equipoPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel noConnection;
    // End of variables declaration//GEN-END:variables
}
